add the detect-root-ca

diff --git a/actions/action.yaml b/actions/action.yaml
--- a/actions/action.yaml
+++ b/actions/action.yaml
@@ -4,22 +4,22 @@ description: Detect unsafe root CA from production files
 runs:
   using: composite
   steps:
-    - name: 🔍 Check for CA in Docker based files
-      shell: bash
-      run: |
-        echo "jjjjjjjjj"
-        exists=$(find . \
-          -type f \
-          -name '*[dD]ocker*' \
-          -exec grep -il 'https://netfree.link/dl/unix-ca.sh' {} +)
-        echo "tryyyyyy"
+    # - name: 🔍 Check for CA in Docker based files
+    #   shell: bash
+    #   run: |
+    #     echo "jjjjjjjjj"
+    #     exists=$(find . \
+    #       -type f \
+    #       -name '*[dD]ocker*' \
+    #       -exec grep -il 'https://netfree.link/dl/unix-ca.sh' {} +)
+    #     echo "tryyyyyy"
 
-        if [ "${exists}" ]; then
-          echo "Root CA found in [${exists}], failing..."
-          exit 1
-        else
-          echo "No root CA detected"
-        fi
+    #     if [ "${exists}" ]; then
+    #       echo "Root CA found in [${exists}], failing..."
+    #       exit 1
+    #     else
+    #       echo "No root CA detected"
+    #     fi
 
     - name: 🔍 Check for trusted hosts
       shell: bash
